### ISSUE TITLE
运行test 里面的launch会报错

### ISSUE THREAD

**Issue by maodougai** [peiyu-cui/uav_motion_planning#3]
setting /run_id to 30cbf4e4-c01e-11ef-a7dc-45a32238cf62
process[rosout-1]: started with pid [86211]
started core service [/rosout]
ERROR: cannot launch node of type [test/test_astar_searching]: Cannot locate node of type [test_astar_searching] in package [test]. Make sure file exists in package path and permission is set to executable (chmod +x)
![d36a7d8a-299d-4256-be4e-d503be43c9a7](https://github.com/user-attachments/assets/f1134f31-3bb3-4105-90ac-ffe8a927d2f2)

**Comment by maodougai** [comment]
把src/planner/test 的 CMakeList文件进行相应的修改并重新编译即可

**Comment by 2WangZhen3** [comment]
请问如何修改
